mod lecture1;
mod lecture2;
mod lecture3;
//pub use lecture1::hangman::warhammer as lecture1;
//pub use lecture1::add_n::add_n as lecture1;
//pub use lecture2::partone::main_lecture2 as excercie;
// pub use lecture2::parttwo::rdiffmain as excercie;
// pub use lecture2::rwcmain::rwcmain as excercie;
// pub use lecture2::conway::main as excercie;
pub use lecture3::linked_list::linkedmain as excercie;
